[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.63.0",
    "langchain-docling>=2.0.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "transformers>=4.57.3",
]
